
FROM php:8.2-fpm
WORKDIR /var/www/html
RUN docker-php-ext-install pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN apt-get update && apt-get install -y supervisor && \
    mkdir -p /var/log/supervisor
COPY . /var/www/html
RUN composer install
COPY ./worker.conf /etc/supervisor/conf.d/
CMD ["/usr/bin/supervisord", "-n"]
