version: '3'
services:
  app:
    image: 'php:8.2-fpm'
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
  web:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/laravel.conf
    depends_on:
      - app
    networks:
      - laravel
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8085:80
    environment:
      PMA_HOST: mysql
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - laravel
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
networks:
  laravel:
